# Generated by Django 3.2.7 on 2022-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchastore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
