# Generated by Django 3.2.7 on 2022-04-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'academy',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=200)),
                ('contest_type', models.CharField(max_length=30)),
                ('contest_info', models.TextField()),
                ('contest_status', models.CharField(default=1, max_length=10)),
                ('contest_organizer', models.CharField(max_length=100)),
                ('contest_time', models.CharField(max_length=50)),
                ('contest_stage', models.CharField(max_length=20)),
                ('contest_ctime', models.CharField(max_length=30)),
                ('contest_img_path', models.CharField(max_length=200)),
                ('contest_pt', models.CharField(max_length=10)),
                ('audit', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contest',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=150)),
                ('file_user_id', models.CharField(max_length=30)),
                ('file_ctime', models.CharField(max_length=30)),
                ('file_user_name', models.CharField(max_length=100)),
                ('file_size', models.CharField(default='0KB', max_length=20)),
            ],
            options={
                'db_table': 'file',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('ctime', models.CharField(max_length=30)),
                ('come_from', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=20)),
                ('img_path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'info',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_c_id', models.CharField(max_length=50)),
                ('tname', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.contest')),
            ],
            options={
                'db_table': 'match',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_c_id', models.CharField(max_length=20)),
                ('t_name', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=50)),
                ('head', models.BooleanField(default=False)),
                ('c_name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.contest')),
            ],
            options={
                'db_table': 'team',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Tyep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('identify', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='学生', max_length=30)),
                ('academy', models.CharField(max_length=30)),
                ('specialty', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=15)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('permissions', models.CharField(default=0, max_length=5)),
                ('qualify_apply', models.IntegerField()),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'user',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('file_path', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.contest')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.team')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='W_Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default=0, max_length=30)),
                ('qualify', models.BooleanField(default=False)),
                ('medal', models.CharField(max_length=50)),
                ('stage', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.match')),
            ],
            options={
                'verbose_name': '获奖、晋级表',
                'db_table': 'wq',
            },
        ),
        migrations.CreateModel(
            name='UWQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.contest')),
            ],
            options={
                'db_table': 'uwq',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('teacher', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.contest')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.team')),
            ],
            options={
                'db_table': 'registration',
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.team'),
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user')),
            ],
            options={
                'verbose_name': '确认码',
                'db_table': 'confirmstring',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user')),
            ],
            options={
                'db_table': 'apply',
            },
        ),
    ]
