# Generated by Django 3.2.7 on 2022-02-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=200)),
                ('contest_type', models.CharField(max_length=30)),
                ('contest_info', models.TextField()),
                ('contest_status', models.BooleanField(default=True)),
                ('contest_organizer', models.CharField(max_length=100)),
                ('contest_time', models.CharField(max_length=50)),
                ('contest_stage', models.CharField(max_length=20)),
                ('contest_ctime', models.CharField(max_length=30)),
                ('contest_img_path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=150)),
                ('file_user_id', models.CharField(max_length=30)),
                ('file_ctime', models.CharField(max_length=30)),
                ('file_user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20)),
                ('identify', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='学生', max_length=30)),
                ('academy', models.CharField(default='计算机', max_length=30)),
                ('specialty', models.CharField(default='软件工程', max_length=40)),
                ('grade', models.CharField(default='2018', max_length=15)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'user',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user')),
            ],
            options={
                'verbose_name': '确认码',
                'db_table': 'confirmstring',
                'ordering': ['-c_time'],
            },
        ),
    ]
